TARGET_ARCH_VARIANT = armv7-a-neon

# for NEON HW control. Sava Chan (26676)
MTK_NEON_SUPPORT=yes

MTK_SWIP_VORBIS=yes

MTK_ENABLE_MD1=yes


MTK_HWC_VERSION = 0.3 


MTK_MMUMAP_SUPPORT = yes 

MTK_VOICE_UNLOCK_SUPPORT = no



MTK_DATAUSAGE_SUPPORT = no 


MTK_DATAUSAGELOCKSCREENCLIENT_SUPPORT = no 

MTK_BATTERY_NO_HAL=yes

MTK_RTC_NO_HAL=yes

MTK_VIDEO_1080P = yes 
LINUX_KERNEL_VERSION = kernel-3.4

MTK_DISP_COMMON_PLATFORM=yes

MTK_MD1_SUPPORT = 2

MTK_MDP_MHAL = yes

LEGACY_DFO_GEN=yes

MTK_USES_VR_DYNAMIC_QUALITY_MECHANISM=yes

MTK_SEC_SECRO_AC_SUPPORT=no
ALWAYSON_DFOSET=no
MTK_PERMISSION_CONTROL = yes
MTK_MOBILE_MANAGEMENT = yes
MTK_PASSPOINT_R1_SUPPORT = no

MTK_CAM_FACEBEAUTY_SUPPORT = yes

MTK_IPO_MDRST_SUPPORT = yes