#ifndef _MT_GPIO_EXT_H_
#define _MT_GPIO_EXT_H_

#define MT_GPIO_EXT_START MT_GPIO_BASE_MAX
typedef enum GPIO_PIN_EXT
{    
	//MT_GPIO_EXT_START = MT_GPIO_BASE_MAX,
	MT_GPIO_EXT_MAX = MT_GPIO_EXT_START
}GPIO_PIN_EXT;

typedef enum GPIO_PIN_EXT1
{    
    //MT_GPIO_EXT_START = MT_GPIO_BASE_MAX,
	MT_GPIO_EXT1_MAX = MT_GPIO_EXT_START
}GPIO_PIN_EXT1;    
#define MT_GPIO_MAX_PIN MT_GPIO_EXT_MAX

#endif //_MT_GPIO_EXT_H_
