#ifndef __MT_IRQ_H
#define __MT_IRQ_H

#define NR_GIC_SGI              16
#define NR_GIC_PPI              16
#define MT_NR_SPI           (128)
#define NR_MT_IRQ_LINE      (NR_GIC_SGI + NR_GIC_PPI + MT_NR_SPI) 
#define GIC_PRIVATE_SIGNALS     32 
#define GIC_PPI_OFFSET          (27)
#define GIC_PPI_GLOBAL_TIMER    (GIC_PPI_OFFSET + 0)
#define GIC_PPI_LEGACY_FIQ      (GIC_PPI_OFFSET + 1)
#define GIC_PPI_PRIVATE_TIMER   (GIC_PPI_OFFSET + 2)
#define GIC_PPI_WATCHDOG_TIMER  (GIC_PPI_OFFSET + 3)
#define GIC_PPI_LEGACY_IRQ      (GIC_PPI_OFFSET + 4)

#define MT_L2CCINTR_IRQ_ID              (GIC_PRIVATE_SIGNALS + 0)
#define MT_SCUEVABORT_IRQ_ID            (GIC_PRIVATE_SIGNALS + 1)
#define MT_NEON_EXCEPTION0_IRQ_ID       (GIC_PRIVATE_SIGNALS + 2)
#define MT_NEON_EXCEPTION1_IRQ_ID       (GIC_PRIVATE_SIGNALS + 3)
#define MT_CA9MP_PARITYFAIL0_IRQ_ID     (GIC_PRIVATE_SIGNALS + 4)
#define MT_CA9MP_PARITYFAIL1_IRQ_ID     (GIC_PRIVATE_SIGNALS + 5)
#define MT_CA9MP_PARITYFAIL2_IRQ_ID     (GIC_PRIVATE_SIGNALS + 6)
#define MT_PMUIRQ0_IRQ_ID               (GIC_PRIVATE_SIGNALS + 7)
#define MT_PMUIRQ1_IRQ_ID               (GIC_PRIVATE_SIGNALS + 125)
#define MT_NCTIIRQ0_IRQ_ID              (GIC_PRIVATE_SIGNALS + 126)
#define MT_NCTIIRQ1_IRQ_ID              (GIC_PRIVATE_SIGNALS + 127)

#define MT_USB0_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 8)
#define MT_USB1_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 9)
#define MT_DSI_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 10)
#define MT_DPI_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 11)
#define MT_TVE_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 12)
#define MT_TVC_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 13)
#define MT_CAM_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 14)
#define MT_CAM_IRQ_LINE                 MT_CAM_IRQ_ID
#define MT_CRZ_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 15)
#define MT_JPEG_CODEC_IRQ_ID            (GIC_PRIVATE_SIGNALS + 16)
#define MT_EIS_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 17)
#define MT_LCD_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 18)
#define MT_TV_ROT_IRQ_ID                (GIC_PRIVATE_SIGNALS + 19)
#define MT_ROT_DMA_IRQ_ID               (GIC_PRIVATE_SIGNALS + 20)
#define MT_OVL_JPG_DMA_IRQ_ID           (GIC_PRIVATE_SIGNALS + 21)
#define MT_SCAM_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 22)
#define MT_AFE_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 23)
#define MT_MD_WDT_DSP_IRQ_ID            (GIC_PRIVATE_SIGNALS + 24)
#define MT_MD_WDT_IRQ_ID                (GIC_PRIVATE_SIGNALS + 25)
#define MT_DMA_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 26)
#define MT_WDT_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 27)
#define MT_SMI_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 28)
#define MT_SLEEP_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 29)
#define MT_TS_IRQ_ID                    (GIC_PRIVATE_SIGNALS + 30)
#define MT_TS_BATCH_IRQ_ID              (GIC_PRIVATE_SIGNALS + 31)
#define MT_LOWBATTERY_IRQ_ID            (GIC_PRIVATE_SIGNALS + 32)
#define MT_DCC_APARM_IRQ_ID             (GIC_PRIVATE_SIGNALS + 33)
#define MT_APARM_CTI_IRQ_ID             (GIC_PRIVATE_SIGNALS + 34)
#define MT_APARM_DOMAIN_IRQ_ID          (GIC_PRIVATE_SIGNALS + 35)
#define MT_APARM_DECERR_IRQ_ID          (GIC_PRIVATE_SIGNALS + 36)
#define MT_ACCDET_IRQ_ID                (GIC_PRIVATE_SIGNALS + 37)
#define MT_RTC_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 38)
#define MT_SIM0_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 39)
#define MT_SIM1_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 40)
#define MT_PWM_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 41)
#define MT_THERM_CTR_IRQ_ID             (GIC_PRIVATE_SIGNALS + 42)
#define MT_AP_CCIF_IRQ_ID               (GIC_PRIVATE_SIGNALS + 43)
#define MT_MSDC1_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 44)
#define MT_MSDC3_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 45)
#define MT_MSDC2_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 46)
#define MT_MSDC0_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 47)
#define MT_AP_HIF_IRQ_ID                (GIC_PRIVATE_SIGNALS + 48)
#define MT_I2C0_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 49)
#define MT_I2C1_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 50)
#define MT_UART1_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 51)
#define MT_UART2_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 52)
#define MT_UART3_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 53)
#define MT_UART4_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 54)
#define MT_NFIECC_IRQ_ID                (GIC_PRIVATE_SIGNALS + 55)
#define MT_NFI_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 56)
#define MT_GPT_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 57)
#define MT_APARM_GPTTIMER_IRQ_LINE      MT_GPT_IRQ_ID
#define MT_GDMA1_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 58)
#define MT_GDMA2_IRQ_ID                 (GIC_PRIVATE_SIGNALS + 59)
#define MT_DMA_AP_HIF_IRQ_ID            (GIC_PRIVATE_SIGNALS + 60)
#define MT_DMA_MD_HIF_IRQ_ID            (GIC_PRIVATE_SIGNALS + 61)
#define MT_DMA_SIM0_IRQ_ID              (GIC_PRIVATE_SIGNALS + 62)
#define MT_DMA_SIM1_IRQ_ID              (GIC_PRIVATE_SIGNALS + 63)
#define MT_DMA_IRDA_IRQ_ID              (GIC_PRIVATE_SIGNALS + 64)
#define MT_DMA_UART0_TX_IRQ_ID          (GIC_PRIVATE_SIGNALS + 65)
#define MT_DMA_UART0_RX_IRQ_ID          (GIC_PRIVATE_SIGNALS + 66)
#define MT_DMA_UART1_TX_IRQ_ID          (GIC_PRIVATE_SIGNALS + 67)
#define MT_DMA_UART1_RX_IRQ_ID          (GIC_PRIVATE_SIGNALS + 68)
#define MT_DMA_UART2_TX_IRQ_ID          (GIC_PRIVATE_SIGNALS + 69)
#define MT_DMA_UART2_RX_IRQ_ID          (GIC_PRIVATE_SIGNALS + 70)
#define MT_KP_IRQ_ID                    (GIC_PRIVATE_SIGNALS + 71)
#define MT_IRDA_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 72)
#define MT_I2C_DUAL_IRQ_ID              (GIC_PRIVATE_SIGNALS + 73)
#define MT_SMI_LARB0_VAMAU_IRQ_ID       (GIC_PRIVATE_SIGNALS + 74)
#define MT_SMI_LARB0_MMU_IRQ_ID         (GIC_PRIVATE_SIGNALS + 75)
#define MT_SMI_LARB1_VAMAU_IRQ_ID       (GIC_PRIVATE_SIGNALS + 76)
#define MT_SMI_LARB1_MMU_IRQ_ID         (GIC_PRIVATE_SIGNALS + 77)
#define MT_SMI_LARB2_VAMAU_IRQ_ID       (GIC_PRIVATE_SIGNALS + 78)
#define MT_SMI_LARB2_MMU_IRQ_ID         (GIC_PRIVATE_SIGNALS + 79)
#define MT_SPI_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 80)
#define MT_VENC_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 81)
#define MT_VDEC_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 82)
#define MT_CSI2_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 83)
#define MT_R_DMA0_IRQ_ID                (GIC_PRIVATE_SIGNALS + 84)
#define MT_RESZ_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 85)
#define MT_DISP_MDP_IRQ_ID              (GIC_PRIVATE_SIGNALS + 86)
#define MT_G2D_IRQ_ID                   (GIC_PRIVATE_SIGNALS + 87)
#define MT_MFG_THALIA_IRQ_ID            (GIC_PRIVATE_SIGNALS + 88)
#define MT_LARB3_VAMAU_IRQ_ID           (GIC_PRIVATE_SIGNALS + 89)
#define MT_LARB3_MMU_IRQ_ID             (GIC_PRIVATE_SIGNALS + 90)
#define MT_AFE_MCU_IRQ_ID               (GIC_PRIVATE_SIGNALS + 91)
#define MT_DMA_FIQ_IRQ_ID               (GIC_PRIVATE_SIGNALS + 92)
#define MT_MD_UART2_IRQ_ID              (GIC_PRIVATE_SIGNALS + 93)
#define MT_MD_UART1_IRQ_ID              (GIC_PRIVATE_SIGNALS + 94)
#define MT_EINT_IRQ_ID                  (GIC_PRIVATE_SIGNALS + 96)
#define MT_EINT_DIRECT0_IRQ_ID          (GIC_PRIVATE_SIGNALS + 97)
#define MT_EINT_DIRECT1_IRQ_ID          (GIC_PRIVATE_SIGNALS + 98)
#define MT_EINT_DIRECT2_IRQ_ID          (GIC_PRIVATE_SIGNALS + 99)
#define MT_EINT_DIRECT3_IRQ_ID          (GIC_PRIVATE_SIGNALS + 100)
#define MT_EINT_DIRECT4_IRQ_ID          (GIC_PRIVATE_SIGNALS + 101)
#define MT_EINT_DIRECT5_IRQ_ID          (GIC_PRIVATE_SIGNALS + 102)
#define MT_EINT_DIRECT6_IRQ_ID          (GIC_PRIVATE_SIGNALS + 103)
#define MT_EINT_DIRECT7_IRQ_ID          (GIC_PRIVATE_SIGNALS + 104)

#endif  /* !__MT_IRQ_H */
